export const Colors = {
  primary: "#0a1e3f",
  secondary: "#FF6B5D",
  warning: "#cc475a",
  
  dark: {
    text: "#D9D9D9",
    secondaryTitle: "#FF6B5D",
    secondarytitle: "#FF6B5D",
    button1: "#FF6B5D",
    button2: "#FFFFFF",
    btnText: "#0a1e3f",
    title: "#F4F7FA",
    background: "#0a1e3f",
    navBackground: "#0a1e3f",
    iconColor: "#9E9E9E",
    iconColorFocused: "#FF6B5D",
    uiBackground: "#FFFFFF",
    recorderBG: "#0A1E3F",
    outerCircle: "#FFFFFF",
    innerCircle: "#FFFFFF",
    checkpoints:"#FFFFFF",
    settings: "#FF6B5D"
  },
  light: {
    text: "#FF6B5D",
    secondaryTitle: "#FF6B5D",
    secondarytitle: "#0A1E3F",
    secondaryText: "#0A1E3F",
    title: "#0A1E3F",
    button1: "#FF6B5D",
    button2: "#0A1E3F",
    btnText: "#FFFFFF",
    background: "#FFFFFF",
    navBackground: "#FFFFFF",
    iconColor: "#9E9E9E",
    iconColorFocused: "#FF6B5D",
    uiBackground: "#0A1E3F",
    recorderBG: "#f8f9ff",
    outerCircle: "#0A1E3F",
    innerCircle: "#FF6B5D",
    checkpoints:"blue",
    settings: "#0A1E3F"
  },
}